# Generated by Django 5.2.3 on 2025-06-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipeTitle', models.CharField(max_length=100)),
                ('recipeDescription', models.TextField()),
                ('recipeIngredients', models.TextField()),
                ('recipeInstructions', models.TextField()),
                ('recipeImage', models.ImageField(upload_to='media/recipe')),
            ],
        ),
    ]
