# Generated by Django 5.2.5 on 2025-08-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='enrolled_courses',
            field=models.ManyToManyField(to='academics.course'),
        ),
    ]
