# Generated by Django 5.2.4 on 2025-07-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('student_name', models.CharField(max_length=100, null=True)),
                ('student_roll', models.IntegerField(null=True)),
                ('student_age', models.PositiveBigIntegerField(null=True)),
                ('student_address', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
