# Generated by Django 5.2.3 on 2025-06-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumemodel',
            name='profilePic',
            field=models.ImageField(upload_to=''),
        ),
    ]
