# Generated by Django 5.2.3 on 2025-06-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_resumemodel_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumemodel',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='company',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='degree',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='experience',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='fullName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='graduationYear',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='hobbies',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='institute',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='phone',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='position',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='profilePic',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='skills',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='summary',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
