# Generated by Django 5.2.3 on 2025-06-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_resumemodel_address_alter_resumemodel_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumemodel',
            name='graduationYear',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
