# Generated by Django 5.2.3 on 2025-06-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_alter_resumemodel_graduationyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumemodel',
            name='achievements',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='phone',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
