# Generated by Django 5.2.1 on 2025-07-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingaccountmodel',
            name='user_types',
        ),
        migrations.AddField(
            model_name='pendingaccountmodel',
            name='user_type',
            field=models.CharField(choices=[('Employer', 'Employer'), ('Candidate', 'Candidate')], null=True),
        ),
        migrations.AlterField(
            model_name='pendingaccountmodel',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accept', 'Accept'), ('Rejected', 'Rejected')], null=True),
        ),
    ]
