# Generated by Django 5.2.1 on 2025-07-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0002_remove_pendingaccountmodel_user_types_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='user_types',
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Employer', 'Employer'), ('Candidate', 'Candidate')], null=True),
        ),
    ]
